server:
  port: 8070

spring:
  application:
    name: config-server
  profiles:
    active: dev
  cloud:
   config:
     server:
       git:
         uri: https://github.com/GodLikeZeal/zealsay-config.git
     label: master
     profile: ${spring.profiles.active}
  output:
    ansi:
      enabled: always


---
spring:
  profiles: dev
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8071/eureka/